# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_packages:
  - covr

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  # units/udunits2 dependency:
  - sudo apt-get install --yes libudunits2-dev
  # sf dependencies:
  - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev

after_script::
  - Rscript -e 'library(magrittr); c14bazAAR::get_all_dates() %>% c14bazAAR::calibrate() %>% c14bazAAR::estimate_spatial_quality() %>% c14bazAAR::rm_doubles(mark = TRUE) %>% c14bazAAR::thesaurify()'

after_success:
  - Rscript -e 'library(covr); codecov()'
